name: 'setup'
description: 'Setup node & pnpm'

runs:
  using: 'composite'
  steps:
    - name: Get node & pnpm version
      shell: bash
      run: |
        pnpm_version=$(cat ./package.json | jq -r .engines.pnpm)
        node_version=$(cat ./package.json | jq -r .engines.node)
        echo "PNPM_VERSION=${pnpm_version}" >> $GITHUB_ENV
        echo "NODE_VERSION=${node_version}" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      id: pnpm-install
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Install Playwright
      shell: bash
      run: pnpx playwright install --with-deps
