name: 'Code test'
on: [pull_request]
jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: lint
        run: pnpm lint

      - name: test
        run: pnpm test

      - name: type
        run: pnpm type

      - name: e2e
        run: pnpm e2e
