name: 'Code test'
on: [pull_request]
jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/pnpm-install/action

      - name: jest
        run: pnpm test

      - name: tsc
        run: pnpm type
