name: CI
on: [pull_request]
jobs:
  CI:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Node version
        id: node_version
        run: |
          PACKAGE_JSON=`cat ./package.json`
          PACKAGE_JSON="${PACKAGE_JSON//'%'/'%25'}"
          PACKAGE_JSON="${PACKAGE_JSON//$'\n'/'%0A'}"
          PACKAGE_JSON="${PACKAGE_JSON//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$PACKAGE_JSON"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ fromJson(steps.node_version.outputs.packageJson).volta.node }}
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'

      - name: node_modules install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: node_modules
        run: npm ls --depth=0

      - name: jest
        run: npm run test

      - name: tsc
        run: npm run tsc
