name: 'Code test'
on: [pull_request]
jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Install Playwright
        shell: bash
        run: pnpx playwright install --with-deps

      - name: e2e
        run: pnpm e2e

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
